export const ActionTypes = {
    SET_CLIENTS : "SET_CLIENTS",
    SELECTED_CLIENT : "SELECTED_CLIENT",
    REMOVE_SELECTED_CLIENT : "REMOVE_SELECTED_CLIENT",
};

export const DeviceActionTypes = {
    SET_DEVICES : "SET_DEVICES",
    SELECTED_DEVICE : "SELECTED_DEVICE",
    REMOVE_SELECTED_DEVICE : "REMOVE_SELECTED_DEVICE",
};

